# Generated by Django 4.2.7 on 2023-12-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_jobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('careerImage', models.ImageField(blank=True, null=True, upload_to='media/career')),
            ],
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
