# Generated by Django 4.2.7 on 2023-12-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_careermodel_alter_jobmodel_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
